### ISSUE TITLE
Benchmark File Unavailable

### ISSUE THREAD

**Issue by pprp** [kmdanielduan/TransNASBench#6]
Hi, @yawen-d , Thanks for your great job!

I am interested in this Benchmark but I can't access the `transnas-bench_v10141024.pth` in https://www.noahlab.com.hk/opensource/vega/page/doc.html?path=datasets/transnasbench101

This link is invalid: https://box.saas.huaweicloud.com/p/b31f2ecde9d19e5261cd76d55fc0804f

Looking forward to your reply, thanks again

**Comment by Tongzhou0101** [comment]
Same problem here. Could you please provide a valid link for downloading the file? Thanks!

**Comment by yawen-d** [comment]
Hi both! I updated the README.md to include a Google Drive Folder for the file release. Hope this helps!

The link is https://drive.google.com/drive/folders/1HlLr2ihZX_ZuV3lJX_4i7q4w-ZBdhJ6o?usp=share_link

**Comment by pprp** [comment]
@yawen-d Thank you for your reply!

**Comment by Tongzhou0101** [comment]
Thanks! @yawen-d
